In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
wine=datasets.load_wine()

In [22]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [17]:
x=wine.data
x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [12]:
y=wine.target

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=2)
x_train

array([[1.220e+01, 3.030e+00, 2.320e+00, ..., 6.600e-01, 1.830e+00,
        5.100e+02],
       [1.277e+01, 3.430e+00, 1.980e+00, ..., 7.000e-01, 2.120e+00,
        3.720e+02],
       [1.336e+01, 2.560e+00, 2.350e+00, ..., 7.000e-01, 2.470e+00,
        7.800e+02],
       ...,
       [1.349e+01, 1.660e+00, 2.240e+00, ..., 9.800e-01, 2.780e+00,
        4.720e+02],
       [1.363e+01, 1.810e+00, 2.700e+00, ..., 1.280e+00, 2.880e+00,
        1.310e+03],
       [1.358e+01, 2.580e+00, 2.690e+00, ..., 7.400e-01, 1.800e+00,
        7.500e+02]])

In [33]:
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
# n=GaussianNB()
gnb=GaussianNB()
gnb.fit(x_train,y_train)
y_pred=gnb.predict(x_test)

In [25]:
x_train[1]

array([ 12.77,   3.43,   1.98,  16.  ,  80.  ,   1.63,   1.25,   0.43,
         0.83,   3.4 ,   0.7 ,   2.12, 372.  ])

In [26]:
a=gnb.predict([[ 12.77,   3.43,   1.98,  16.  ,  80.  ,   1.63,   1.25,   0.43,
         0.83,   3.4 ,   0.7 ,   2.12, 372.  ]])

In [27]:
a

array([1])

In [30]:
x_train


array([[1.220e+01, 3.030e+00, 2.320e+00, ..., 6.600e-01, 1.830e+00,
        5.100e+02],
       [1.277e+01, 3.430e+00, 1.980e+00, ..., 7.000e-01, 2.120e+00,
        3.720e+02],
       [1.336e+01, 2.560e+00, 2.350e+00, ..., 7.000e-01, 2.470e+00,
        7.800e+02],
       ...,
       [1.349e+01, 1.660e+00, 2.240e+00, ..., 9.800e-01, 2.780e+00,
        4.720e+02],
       [1.363e+01, 1.810e+00, 2.700e+00, ..., 1.280e+00, 2.880e+00,
        1.310e+03],
       [1.358e+01, 2.580e+00, 2.690e+00, ..., 7.400e-01, 1.800e+00,
        7.500e+02]])

In [34]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))

[[20  1  0]
 [ 0 22  0]
 [ 0  1 15]]


In [35]:
print(accuracy_score(y_test,y_pred))

0.9661016949152542


# k_nearest

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
from sklearn import metrics
print("Accuracy",metrics.accuracy_score(y_pred,y_test))


Accuracy 0.6949152542372882


In [43]:
df=pd.read_csv('shirts.csv')
df.head()

Height  Weight Tshirt_size
0     158      58           M
1     158      59           M
2     158      63           M
3     160      59           M
4     160      60           M

In [51]:
x=df[['Height','Weight']]
# x
y=df['Tshirt_size']
y

0     M
1     M
2     M
3     M
4     M
5     M
6     M
7     L
8     L
9     L
10    L
11    L
12    L
13    L
14    L
15    L
16    L
17    L
Name: Tshirt_size, dtype: object

In [52]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [53]:
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=2)
x_train

Height  Weight
3      160      59
1      158      59
12     168      62
7      160      64
14     168      66
2      158      63
11     165      65
6      163      61
17     170      68
13     168      63
15     170      63
8      163      64

In [58]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
from sklearn import metrics
print("Accuracy",metrics.accuracy_score(y_pred,y_test))


Accuracy 1.0


In [62]:
knn.predict([[160,59]])

array([1])